/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import de.javasoft.plaf.synthetica.SyntheticaSimple2DLookAndFeel;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import sun.swing.ImageIconUIResource;

/**
 *
 * @author Tharindu Kalubowila
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    JButton button[] = new JButton[9];
    boolean x, o;
    boolean lock[] = new boolean[9];
    Human human;
    Machine machine;
    int count,plyr1=0,plyr2=0,total=0;
    String option;

    public Interface() throws UnsupportedLookAndFeelException {
        try {
            UIManager.setLookAndFeel(new SyntheticaSimple2DLookAndFeel());
        } catch (ParseException ex) {
            Logger.getLogger(StartUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        button = new JButton[9];
        lock = new boolean[9];
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        B6 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        player1 = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        Totalgames = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Player1marks = new javax.swing.JLabel();
        Player2marks = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        B6.setBackground(new java.awt.Color(204, 204, 255));
        B6.setFont(new java.awt.Font("Trajan Pro", 0, 70)); // NOI18N
        B6.setForeground(new java.awt.Color(204, 51, 0));
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B1.setBackground(new java.awt.Color(204, 204, 255));
        B1.setFont(new java.awt.Font("Trajan Pro", 0, 70)); // NOI18N
        B1.setForeground(new java.awt.Color(204, 51, 0));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(204, 204, 255));
        B2.setFont(new java.awt.Font("Trajan Pro", 0, 70)); // NOI18N
        B2.setForeground(new java.awt.Color(204, 51, 0));
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B4.setBackground(new java.awt.Color(204, 204, 255));
        B4.setFont(new java.awt.Font("Trajan Pro", 0, 70)); // NOI18N
        B4.setForeground(new java.awt.Color(204, 51, 0));
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setBackground(new java.awt.Color(204, 204, 255));
        B5.setFont(new java.awt.Font("Trajan Pro", 0, 70)); // NOI18N
        B5.setForeground(new java.awt.Color(204, 51, 0));
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B3.setBackground(new java.awt.Color(204, 204, 255));
        B3.setFont(new java.awt.Font("Trajan Pro", 0, 70)); // NOI18N
        B3.setForeground(new java.awt.Color(204, 51, 0));
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B7.setBackground(new java.awt.Color(204, 204, 255));
        B7.setFont(new java.awt.Font("Trajan Pro", 0, 70)); // NOI18N
        B7.setForeground(new java.awt.Color(204, 51, 0));
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B8.setBackground(new java.awt.Color(204, 204, 255));
        B8.setFont(new java.awt.Font("Trajan Pro", 0, 70)); // NOI18N
        B8.setForeground(new java.awt.Color(204, 51, 0));
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setBackground(new java.awt.Color(204, 204, 255));
        B9.setFont(new java.awt.Font("Trajan Pro", 0, 70)); // NOI18N
        B9.setForeground(new java.awt.Color(204, 51, 0));
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        Title.setText("Player 1 Vs Player 2");

        player1.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        player1.setText("Player 1");

        player2.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        player2.setText("Player 2");

        Totalgames.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        Totalgames.setText("Total Games");

        jButton1.setFont(new java.awt.Font("Vijaya", 3, 18)); // NOI18N
        jButton1.setText("New Game");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Vijaya", 3, 18)); // NOI18N
        jButton2.setText("Exit Game");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Player1marks.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        Player1marks.setText("0");

        Player2marks.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        Player2marks.setText("0");

        Total.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        Total.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(player1)
                            .addComponent(Player1marks)
                            .addComponent(player2)
                            .addComponent(Player2marks)
                            .addComponent(Totalgames)
                            .addComponent(Total)))
                    .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {B1, B2, B3, B4, B5, B6, B7, B8, B9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(B2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(player1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Player1marks)
                        .addGap(18, 18, 18)
                        .addComponent(player2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Player2marks)
                        .addGap(18, 18, 18)
                        .addComponent(Totalgames)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {B1, B2, B3, B4, B5, B6, B7, B8, B9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        set(0);
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        set(1);
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        set(2);
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
        set(3);
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
        set(4);
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
        set(5);
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        // TODO add your handling code here:
        set(6);
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:
        set(7);
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:
        set(8);
    }//GEN-LAST:event_B9ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        initButton();
        setOption(option);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
         StartUp startup = new StartUp();
         startup.setLocation(this.getLocation());
         startup.setVisible(true);
         this.dispose();
         } catch (UnsupportedLookAndFeelException ex) {
         Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
         }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Interface().setVisible(true);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JLabel Player1marks;
    private javax.swing.JLabel Player2marks;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel Totalgames;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel player1;
    private javax.swing.JLabel player2;
    // End of variables declaration//GEN-END:variables

    protected void initButton() {
        count = 0;

        button[0] = B1;
        button[1] = B2;
        button[2] = B3;
        button[3] = B4;
        button[4] = B5;
        button[5] = B6;
        button[6] = B7;
        button[7] = B8;
        button[8] = B9;

        for (int i = 0; i < 9; i++) {
            button[i].setText("");
            lock[i] = false;
        }

    }

    protected void set(int index) {
        switch (option) {
            case "machine":
                if (!lock[index]) {
                    count++;
                    lock[index] = true;
                    if (!x) {
                        button[index].setText("X");
                        //button[index].setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/cross 2.png")));
                        x = true;
                        o = false;
                        if (count == 9) {
                            total++;
                            JOptionPane.showMessageDialog(null, "GAME DRAW", "Game Condition", 1);
                            Total.setText(String.valueOf(total));
                            initButton();
                            setOption("machine");

                        }
                        checkConditionMachine();
                    } else if (!o) {
                        button[index].setText("O");
                        //button[index].setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/circule 2.png")));
                        o = true;
                        x = false;

                        if (count == 9) {
                            total++;
                            JOptionPane.showMessageDialog(null, "GAME DRAW", "Game Condition", 1);
                            Total.setText(String.valueOf(total));
                            initButton();
                            setOption("machine");

                        } else {
                            machine.play("X");
                            machine.setInterface();
                        }

                        checkConditionMachine();

                    }
                }
                break;

            case "human":
                if (!lock[index]) {
                    count++;
                    lock[index] = true;
                    if (!x) {
                        button[index].setText("X");
                        checkConditionHuman();
                        //button[index].setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/cross 2.png")));
                        x = true;
                        o = false;
                    } else if (!o) {
                        button[index].setText("O");
                        checkConditionHuman();
                        //button[index].setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/circule 2.png")));
                        o = true;
                        x = false;
                    }
                }
                break;

            default:
                break;
        }

    }

    private void checkConditionHuman() {
        String status = null;
        status = human.checkCondition();
        if (status == "reset") {
            initButton();
        }
        if (count == 9) {
            total++;
            JOptionPane.showMessageDialog(null, "GAME DRAW", "Game Condition", 1);
            Total.setText(String.valueOf(total));
            initButton();
        }
    }

    protected void setOption(String op) {
        option = op;
        switch (option) {
            case "machine":
                Title.setText("..Machine Vs You..");
                player1.setText("..YOU..");
                player2.setText("..MACHINE..");
                x = true;
                o = false;
                machine = new Machine(this);
                break;
            case "human":
                x = false;
                o = true;
                human = new Human(this);
                
                break;
        }
    }

    private void checkConditionMachine() {
        if (machine.score() == 1) {
            incrementPlayer2();
            JOptionPane.showMessageDialog(null, "MACHINE WON..!", "Game Condition", 1);
            printPlayer2();
            Total.setText(String.valueOf(total));
            initButton();
            machine.ArrayAssignment();
            setOption("machine");
        } else if (machine.score() == -1) {
            incrementPlayer1();
            JOptionPane.showMessageDialog(null, "YOU WON", "Game Condition", 1);
            printPlayer1();
            Total.setText(String.valueOf(total));
            initButton();
            setOption("machine");
            machine.ArrayAssignment();
        }
    }

    void incrementPlayer1() {
        plyr1++;
        total++;
    }

    void printPlayer1() {
        Player1marks.setText(String.valueOf(plyr1));
        Total.setText(String.valueOf(total));
    }

    void incrementPlayer2() {
        plyr2++;
        total++;
    }

    void printPlayer2() {
        Player2marks.setText(String.valueOf(plyr2));
        Total.setText(String.valueOf(total));
    }


}
